version: "3.8"

volumes:
  rabbitmq_data:

services:

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq
 
  ###################################
  # User: The User microservice
  ###################################
  user:
    build:
      context: ./
      dockerfile: user.Dockerfile
    image: jeremygmc/user:esd
    restart: always
    ports:
      - 8000:26257
    environment:
      PYTHONUNBUFFERED: 1

  ###################################
  # Compatibility: The Compatibility microservice
  ###################################
  compat:
    build:
      context: ./
      dockerfile: compat.Dockerfile
    image: jeremygmc/compat:esd
    depends_on:
      - user
    restart: always
    ports:
      - 8001:7100
    environment:
      PYTHONUNBUFFERED: 1

  ###################################
  # Match: The Match microservice
  ###################################
  match:
    build:
      context: ./
      dockerfile: match.Dockerfile
    image: jeremygmc/match:esd
    depends_on:
      - user
    restart: always
    ports:
      - 8002:26257
    environment:
      PYTHONUNBUFFERED: 1
  
  ###################################
  # Date Idea API: The dateideaapi microservice
  ###################################
  dateideaapi:
    build:
      context: ./
      dockerfile: dateideaapi.Dockerfile
    image: jeremygmc/dateideaapi:esd
    depends_on:
      - user
    restart: always
    ports:
      - 5005:5005
    environment:
      PYTHONUNBUFFERED: 1